Feat/start page
leeeeejieun/Dear_Therapy pull request #20
Opened 2024-10-19 14:00 UTC by HJK013

2024-10-19 15:07 UTC, leeeeejieun commented on client/src/App.jsx
return문에서 주석 사용하지 말아주세요. 해당 주석이 화면에 렌더링 되고 있습니다.
`import StartPage from './pages/StartPage';` 상대 경로가 아닌 절대 경로로 import 해주세요.
`../ ./ ` 이런 식의 경로 표현은 상대 경로를 이용하는 겁니다.
StartPage 컴포넌트는 App.jsx가 아닌 Router.js에 정의해주세요. Router.js는 페이지 컴포넌트들이 모이는 파일입니다.

2024-10-19 15:13 UTC, leeeeejieun commented on client/src/components/UserContext.jsx
UserContext가 아닌 UserProvider를 export 하셔야 합니다.

2024-10-19 15:30 UTC, leeeeejieun commented on client/src/pages/StartPage.jsx
1. 불필요한 코드 삭제 : 해당 페이지에서 사용하지 않는 `axios`, `SERVER_URL` 등의 코드를 제거해주세요
2. CSS로 위치 조정 : 현재 위치 조정을 위해 `<Spacer />` 컴포넌트가 반복적으로 사용되는 것으로 보이는데,  위치 조정은 css로 해주시고 해당 컴포넌트들은 지워주시기 바랍니다.
3. 이미지 파일 경로 설정:  이미지 파일을 src 폴더 또는 public 폴더 중 어느 곳에 넣을지 새온님과 상의 후 일관되게 설정해주세요.
4.  `<SignUpImage src={signUpImage} alt="Sign up decoration" />` 여기 src가 아닌 to를 사용하셔야 합니다.
5. 링크명도 일관되게 지정해주세요.
6. Styled-componets 코드들 들여쓰기 해주세요.
7. 컴포넌트 분리 : componets 폴더 내 하위 폴더를 생성하셔서 그 안에 해당 코드들을 여러 컴포넌트로 분리하고, 이를 StartPage에 합쳐주세요.(새온님 브랜치 확인해보시면 이해 될겁니다.)
8. `background-color: ${props => props.theme.bt_darkbg};` 이런 식으로 코드 수정해주세요.

일단 여기까지 진행해 주시고, 다음주 회의 때 해당 코드에 대해서 자세히 논의해야 할 듯 합니다.

2024-10-19 15:44 UTC, leeeeejieun requested changes
일단 제가 코멘트 단 부분들 반영 부탁드릴게요

2024-10-20 08:53 UTC, leeeeejieun commented on client/src/components/TitleContainer.jsx
> +const Spacer = styled.div`
위치 조정은 CSS로 부탁드릴게요

2024-10-28 07:59 UTC, HJK013 commented
> 일단 제가 코멘트 단 부분들 반영 부탁드릴게요

수정 완료했습니다! 확인 부탁드릴게요

2024-10-29 16:12 UTC, leeeeejieun approved these changes

2024-10-31 05:08 UTC, PSO01 approved these changes

2024-10-31 06:01 UTC, merged