Feat/diary create
leeeeejieun/Dear_Therapy pull request #42
Opened 2024-11-06 13:18 UTC by PSO01

2024-11-06 18:49 UTC, leeeeejieun requested changes
제가 코멘트로 말씀 드린 부분 오늘까지 수정 부탁드릴게요.
코멘트 외에 추가로 수정이 필요한 css 부분은 제가 마무리하겠습니다!

2024-11-06 18:49 UTC, leeeeejieun commented on client/public/images/1.png
이미지 파일은 현재 버킷에 저장되고 있으니 해당 폴더는 삭제해주세요

2024-11-06 18:49 UTC, leeeeejieun commented on client/src/App.jsx
> +import DiaryPage from "pages/DiaryPage";
App.jsx에 있는 DiaryPage 컴포넌트는 지워주세요

2024-11-06 18:49 UTC, leeeeejieun commented on client/src/components/common/Button.jsx
> +        textstyle: css`
카멜 케이스 형식인 textStyle로 작성하셔야 합니다.  iconStyle도 정의 부탁드릴게요.
현재 모바일에선 아이콘 색상이 파란색으로 나타나는 오류가 있습니다. 
다른 파일에서 사용 중인 아이콘도 동일한 문제가 발생하고 있으니, 모든 아이콘에 검정색이 적용되도록 수정해주세요

2024-11-06 18:49 UTC, leeeeejieun commented on client/src/components/common/Button.jsx
> +            top: 508px;
top에서 500px로 위치를 조정하는 것 보단 bottom을 이용해서 조정해 주시면 좋을 듯 합니다.

```
bottom: 0;
left: 50%;
transform: translateX(-50%);
```

이런 식으로 작성하시면 버튼이 화면 정중앙에 위치하게 됩니다 참고해주세요

2024-11-06 18:49 UTC, leeeeejieun commented on client/src/components/diary/BottomNavigation.jsx
> +      <NavButton size="30px"  transform="translateY(3%)"><FaCalendarCheck /></NavButton>
컴포넌트에 props를 전달하는 이유는 `${(props) => props.size}` 이런 식으로 넘겨 받은 값을 css에서 적용할 수 있기 때문입니다. 현재 해당 코드가 적용되고 있지 않은 상태인데,  지금 상태에서도 스타일에 큰 문제가 없어보이니 이 부분은 삭제해주셔도 괜찮을 것 같아요.

2024-11-06 18:49 UTC, leeeeejieun commented on client/src/components/diary/BottomNavigation.jsx
> +      <NavButton><BsBarChartFill /></NavButton>
해당 아이콘들은 클릭 시 페이지 전환이 일어나야 하므로, button 태그가 아닌 Link 태그로 구현해주시는게 좋습니다. 

```
<NavButton to="/graph"><BsBarChartFill /></NavButton>
<NavButton to="/home"><FaCalendarCheck /></NavButton>
<NavButton to="/profile"><FaUser /></NavButton>
```

2024-11-06 18:49 UTC, leeeeejieun commented on client/src/components/diary/BottomNavigation.jsx
> +const NavButton = styled.button`
`const NavButton = styled(Link)` 
이렇게 변경하시면 됩니다.

2024-11-06 18:49 UTC, leeeeejieun commented on client/src/components/diary/ImageUploader.jsx
> +      document.getElementById('img').click();
해당 메서드가 어떤 목적으로 사용되는 지 설명 부탁드릴게요

2024-11-06 18:49 UTC, leeeeejieun commented on client/src/routes/Router.js
Router.jsx 파일이 이미 존재하니 추가로 생성된 해당 파일은 삭제해주시고, 기존 Router.jsx 파일에 작성 부탁드립니다

2024-11-08 08:12 UTC, leeeeejieun approved these changes

2024-11-09 10:00 UTC, HJK013 approved these changes

2024-11-09 10:54 UTC, merged